name: Build Android Kernel 6.6 (DroidSpaces)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: write

    steps:
    - name: Maximize build space
      uses: easimon/maximize-build-space@v5
      with:
        root-reserve-mb: 2048
        swap-size-mb: 1024
        remove-dotnet: 'true'
        remove-android: 'true'
        remove-haskell: 'true'
        remove-codeql: 'true'
        remove-docker-images: 'true'

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y repo python3 git curl build-essential bison flex libssl-dev libelf-dev bc

    - name: Repo Init & Sync
      run: |
        mkdir -p android-kernel
        cd android-kernel
        repo init -u https://android.googlesource.com/kernel/manifest -b common-android15-6.6 --depth=1
        repo sync -c -j$(nproc) --no-clone-bundle --no-tags

    - name: Modify GKI Config for DroidSpaces
      working-directory: ./android-kernel
      run: |
        cat << 'EOF' >> common/arch/arm64/configs/gki_defconfig

        # --- DroidSpaces Configurations ---
        CONFIG_SYSVIPC=y
        CONFIG_POSIX_MQUEUE=y
        CONFIG_IPC_NS=y
        CONFIG_PID_NS=y
        CONFIG_DEVTMPFS=y
        CONFIG_NETFILTER_XT_MATCH_ADDRTYPE=y
        CONFIG_USER_NS=y
        CONFIG_NETFILTER_XT_TARGET_REJECT=y
        CONFIG_NETFILTER_XT_TARGET_LOG=y
        CONFIG_NETFILTER_XT_MATCH_RECENT=y
        CONFIG_IP_SET=y
        CONFIG_IP_SET_HASH_IP=y
        CONFIG_IP_SET_HASH_NET=y
        CONFIG_NETFILTER_XT_SET=y
        CONFIG_TMPFS_POSIX_ACL=y
        CONFIG_TMPFS_XATTR=y
        EOF

    - name: Build Kernel Image
      working-directory: ./android-kernel
      run: |
        tools/bazel --output_user_root="$GITHUB_WORKSPACE/.bazel_cache" build \
          --local_ram_resources=HOST_RAM*0.7 \
          //common:kernel_aarch64/Image.gz

        mkdir -p dist_out
        find bazel-bin/ -name "Image.gz" -type f -exec cp -L {} dist_out/ \;
        test -s dist_out/Image.gz || (echo "Error: Image.gz build failed or empty!" && exit 1)

    - name: Upload Kernel Image
      uses: actions/upload-artifact@v4
      with:
        name: DroidSpaces-Image.gz
        path: android-kernel/dist_out/Image.gz
