name: Build gemini

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: write

    steps:
    - name: Maximize Build Space
      uses: easimon/maximize-build-space@v5
      with:
        root-reserve-mb: 2048
        swap-size-mb: 1024
        temp-reserve-mb: 100
        overprovision-lvm: false
        pv-loop-path: /pv.img
        tmp-pv-loop-path: /mnt/tmp-pv.img
        remove-dotnet: true
        remove-android: true
        remove-haskell: true

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y repo python3 git curl build-essential bison flex libssl-dev libelf-dev bc

    - name: Init and Sync Kernel Source (With Retry)
      run: |
        mkdir -p android-kernel
        cd android-kernel
        repo init -u https://android.googlesource.com/kernel/manifest -b common-android15-6.6 --depth=1

        MAX_RETRIES=3
        RETRY_DELAY=180
        SYNC_SUCCESS=false

        for i in $(seq 1 $MAX_RETRIES); do
          echo "=== 开始第 $i/$MAX_RETRIES 次同步 ==="
          if repo sync -c -j$(nproc) --no-clone-bundle --no-tags; then
            SYNC_SUCCESS=true
            echo "=== 源码同步成功 ==="
            break
          fi

          if [ $i -lt $MAX_RETRIES ]; then
            echo "警告: 第 $i 次同步失败，等待 3 分钟后进行下一次重试..."
            sleep $RETRY_DELAY
          fi
        done

        if [ "$SYNC_SUCCESS" = "false" ]; then
          echo "错误: repo sync 连续失败 $MAX_RETRIES 次，终止流程。"
          exit 1
        fi


    - name: Build Kernel
      run: |
        cd android-kernel
        tools/bazel --output_user_root="$GITHUB_WORKSPACE/.bazel_cache" build \
          --local_ram_resources=HOST_RAM*0.7 \
          --kconfig_add=CONFIG_SYSVIPC=y \
          --kconfig_add=CONFIG_POSIX_MQUEUE=y \
          --kconfig_add=CONFIG_IPC_NS=y \
          --kconfig_add=CONFIG_PID_NS=y \
          --kconfig_add=CONFIG_DEVTMPFS=y \
          --kconfig_add=CONFIG_NETFILTER_XT_MATCH_ADDRTYPE=y \
          --kconfig_add=CONFIG_USER_NS=y \
          --kconfig_add=CONFIG_NETFILTER_XT_TARGET_REJECT=y \
          --kconfig_add=CONFIG_NETFILTER_XT_TARGET_LOG=y \
          --kconfig_add=CONFIG_NETFILTER_XT_MATCH_RECENT=y \
          --kconfig_add=CONFIG_IP_SET=y \
          --kconfig_add=CONFIG_IP_SET_HASH_IP=y \
          --kconfig_add=CONFIG_IP_SET_HASH_NET=y \
          --kconfig_add=CONFIG_NETFILTER_XT_SET=y \
          --kconfig_add=CONFIG_TMPFS_POSIX_ACL=y \
          --kconfig_add=CONFIG_TMPFS_XATTR=y \
          //common:kernel_aarch64/Image.gz

        mkdir -p dist_out
        find bazel-bin/ -name "Image.gz" -type f -exec cp -L {} dist_out/ \;
        test -s dist_out/Image.gz || (echo "Error: Image.gz build failed or empty!" && exit 1)
